<?php


//define('SKIP_CAMPUSCONNECT_CONNECT_TESTS', 1);
//define('SKIP_CAMPUSCONNECT_DIRECTORYTREE_TESTS', 1);
//define('SKIP_CAMPUSCONNECT_ECSSETTINGS_TESTS', 1);
//define('SKIP_CAMPUSCONNECT_EXPORT_TESTS', 1);
//define('SKIP_CAMPUSCONNECT_METADATA_TESTS', 1);
//define('SKIP_CAMPUSCONNECT_PARTICIPANT_TESTS', 1);
//define('SKIP_CAMPUSCONNECT_RECEIVEQUEUE_TESTS', 1);
//define('SKIP_CAMPUSCONNECT_COURSE_TESTS', 1);
//define('SKIP_CAMPUSCONNECT_COURSEFILTER_TESTS',1);
//define('SKIP_CAMPUSCONNECT_PARALLELGROUPS_TESTS', 1);
//define('SKIP_CAMPUSCONNECT_COURSEMEMBERS_TESTS', 1);
